name: Deploy to Render

on:
  push:
    branches:
      - migrate-to-h2

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/your-app-name:latest

    - name: Get Render service ID
      id: render_service
      run: |
        service_id=$(curl -s -H "Authorization: Bearer $RENDER_API_KEY" https://api.render.com/v1/services | jq -r '.[] | select(.name == "your-service-name") | .id')
        echo "::set-output name=service_id::$service_id"

    - name: Deploy to Render
      run: |
        curl -X POST "https://api.render.com/v1/services/${{ steps.render_service.outputs.service_id }}/deploys" \
        -H "Authorization: Bearer $RENDER_API_KEY" \
        -H "Content-Type: application/json" \
        -d '{"clearCache": false}'
